resources:
  - metrics-server/deploy/1.8+/aggregated-metrics-reader.yaml
  - metrics-server/deploy/1.8+/auth-delegator.yaml
  - metrics-server/deploy/1.8+/auth-reader.yaml
  - metrics-server/deploy/1.8+/metrics-apiservice.yaml
  - metrics-server/deploy/1.8+/metrics-server-deployment.yaml
  - metrics-server/deploy/1.8+/metrics-server-service.yaml
  - metrics-server/deploy/1.8+/resource-reader.yaml

# We use the 3.7 because it supports multi-arch manifest:
images:
  - name: k8s.gcr.io/metrics-server-amd64
    newName: gcr.io/k8s-staging-metrics-server/metrics-server
    newTag: v0.3.7
