resources:
  - kubernetes/cluster/addons/fluentd-elasticsearch/es-service.yaml
  - kubernetes/cluster/addons/fluentd-elasticsearch/es-statefulset.yaml
  - kubernetes/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml
  - kubernetes/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
  - kubernetes/cluster/addons/fluentd-elasticsearch/kibana-deployment.yaml
  - kubernetes/cluster/addons/fluentd-elasticsearch/kibana-service.yaml

images:
  - name: gcr.io/fluentd-elasticsearch/fluentd
    newName: carlosedp/fluentd-elasticsearch
    newTag: 1.3.3
  - name: gcr.io/fluentd-elasticsearch/elasticsearch
    newName: carlosedp/docker-elasticsearch-kubernetes
    newTag: 6.6.0
  - name: docker.elastic.co/kibana/kibana-oss
    newName: carlosedp/docker-kibana
    newTag: 6.3.0
