---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sriov-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList":
      [
        {
          "resourceName": "sriov",
          "rootDevices": ["07:00.0", "07:00.1"],
          "sriovMode": true,
          "deviceType": "netdevice"
        }
      ]
    }
